permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 太极熊科技-MakerPanda
  email: makerpanda@163.com
  weibo: 
  github: http://github.com/MakerPanda

# 站点信息
title: Welcome to MakerPanda
description: 文档资料
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /public/img/viewfile.jpg
favicon: /public/img/pandaFlying.png
# google analytics 设置
ga:
  #id: UA-54767140-1
  url: docs.taijipanda.cn

# disqus 设置
disqus:
  shortname: makerpanda-doc
