permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 瑞莎科技-Radxa
  email: support@radxa.com
  weibo: weibo.com/radxa
  github: http://github.com/MakerPanda

# 站点信息
title: Welcome to MakerPanda
description: 文档资料
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://avatars3.githubusercontent.com/u/19486517?v=3&s=200
favicon: 
# google analytics 设置
ga:
  id: UA-54767140-1
  url: docs.taijipanda.cn

# disqus 设置
disqus:
  shortname: radxa-doc
