permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 瑞莎科技-Radxa
  email: support@radxa.com
  weibo: weibo.com/radxa
  github: http://github.com/MakerPanda

# 站点信息
title: Welcome to MakerPanda
description: 文档资料
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://set1.mail.qq.com/cgi-bin/viewfile?f=508D233D4A716902B22DF4AD1E78109BDE2C97369AA1C0080D9C147E03650036BEDB2B485F44CAEFDCB0A34BE6D544230335D9A1A924433DD98FDA14A692C11518C9D30D1B9432164846E34BFC291D128E8DE98C05B6156F236D720898F69FE6&mailid=ZL0526-w0uB35r65%7EGnHjNkdWIMJ65&sid=YOg8PnsalpDWdlsM&net=2340587018
favicon: 
# google analytics 设置
ga:
  id: UA-54767140-1
  url: docs.taijipanda.cn

# disqus 设置
disqus:
  shortname: radxa-doc
